### ISSUE TITLE
i need retrieve all classes name from owl file using owlapi 

### ISSUE THREAD

**Issue by abobkerElmaki** [ignazio1977/owlapiverification#1]
this my code 
package testowl;

import java.io.File;
import java.net.URI;
import java.net.URL;
import java.util.Set;

import org.semanticweb.HermiT.Reasoner;
import org.semanticweb.owlapi.apibinding.OWLManager;
import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLAnnotationSubject;
import org.semanticweb.owlapi.model.OWLClass;
import org.semanticweb.owlapi.model.OWLDataFactory;
import org.semanticweb.owlapi.model.OWLEntity;
import org.semanticweb.owlapi.model.OWLIndividual;
import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;
import org.semanticweb.owlapi.model.OWLOntologyCreationException;
import org.semanticweb.owlapi.model.OWLOntologyManager;
import org.semanticweb.owlapi.reasoner.NodeSet;
import org.semanticweb.owlapi.reasoner.OWLReasoner;
import org.semanticweb.owlapi.reasoner.OWLReasonerFactory;
import org.semanticweb.owlapi.reasoner.structural.StructuralReasonerFactory;
import org.semanticweb.owlapi.util.OWLEntityRemover;

public class myclass {        
        static OWLOntology myOntology ;
        static OWLDataFactory df ;
        static OWLOntologyManager manager ;    
        static IRI ontologyIRI ;
        static File file = new File("C:/travel.owl");
        private OWLOntologyManager manager2;
	    private static OWLOntology ontology;
	    private static OWLDataFactory factory;
	    private static Reasoner reasoner;
    private OWLEntityRemover remover;
	     private static URL url;
	    private static URI uri;
        public static IRI fileURI = IRI.create(file);
        static OWLReasonerFactory reasonerFactory = new StructuralReasonerFactory();
                                         
        @SuppressWarnings("deprecation")
		public static void main(String args[]) throws OWLOntologyCreationException {
                                       
                manager = OWLManager.createOWLOntologyManager(); 
                myOntology = manager.loadOntology(fileURI);
                ontologyIRI = IRI.create("the IRI of the onology"); 
                df = manager.getOWLDataFactory();	
                System.out.println("Loading Ontology...\n"  + myOntology);
                System.out.println("-----------------------");  
                OWLAnnotationSubject enitity =fileURI;
                System.out.println("all classes for travel antology"+ myOntology.getClassesInSignature());
                Set<OWLClass> entity=myOntology.getClassesInSignature();
                for (OWLClass c : myOntology.getClassesInSignature()) {
                    if (c.getIRI().getFragment().equals("Places")){
                    	System.out.println("ASDAS");
                        NodeSet<OWLNamedIndividual> instances = reasoner.getInstances(c, false);
                        System.out.println("ASDYYY"+instances);
                        System.out.println("$%$#%$%"+c.getIRI().getFragment());
                        for (OWLNamedIndividual i : instances.getFlattened()) {
                            System.out.println(i.getIRI().getFragment()); 
                        }
                    }
                }
         //     System.out.println("all classes "+OWLEntity.getIRI().getShortForm());
               
                                  }
                 
         
       
     }
i have problem with null pointer exception 
i need explore Places from http://www.travel.com/ontologies/travel.owl#Places
that's my owl file

**Comment by ignazio1977** [comment]
Your reasoner variable is not initialized.

You don't need a reasoner to list the class names, you can delete the reasoner and the reasoner factory.
